/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mavi.ort.edu.uy.ui;

import javax.swing.UIManager;

/**
 *
 * @author vicentebermudez
 */
public class InitialFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public InitialFrame() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ignored) {
            System.out.println("'Windows look and feel' no se pudo cargar exitosamente");
        }
        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setTechnicBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        setPilotBtn = new javax.swing.JButton();
        setIndividualFumigationBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        setProductBtn1 = new javax.swing.JButton();
        requestBtn = new javax.swing.JButton();
        uploadFumigationBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setTechnicBtn.setText("Alta técnico");
        setTechnicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTechnicBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Gestión de fumigaciones aéreas");

        setPilotBtn.setText("Alta piloto");
        setPilotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPilotBtnActionPerformed(evt);
            }
        });

        setIndividualFumigationBtn.setText("Registro de fumigación individual");
        setIndividualFumigationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setIndividualFumigationBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Salir");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        setProductBtn1.setText("Alta producto");
        setProductBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setProductBtn1ActionPerformed(evt);
            }
        });

        requestBtn.setText("Consulta");
        requestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBtnActionPerformed(evt);
            }
        });

        uploadFumigationBtn.setText("Carga de fumigaciones de archivo");
        uploadFumigationBtn.setToolTipText("");
        uploadFumigationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadFumigationBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(setProductBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadFumigationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(149, 149, 149)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(setIndividualFumigationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(setPilotBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(setTechnicBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(setPilotBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setTechnicBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setProductBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setIndividualFumigationBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requestBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uploadFumigationBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setTechnicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTechnicBtnActionPerformed
        this.setVisible(false);
        new TechnicFrame().setVisible(true);
    }//GEN-LAST:event_setTechnicBtnActionPerformed

    private void setPilotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPilotBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new PilotFrame().setVisible(true);
    }//GEN-LAST:event_setPilotBtnActionPerformed

    private void setIndividualFumigationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setIndividualFumigationBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FumigationRegistryFrame().setVisible(true);
    }//GEN-LAST:event_setIndividualFumigationBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void setProductBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setProductBtn1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductFrame().setVisible(true);
    }//GEN-LAST:event_setProductBtn1ActionPerformed

    private void requestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new QueryFrame().setVisible(true);
    }//GEN-LAST:event_requestBtnActionPerformed

    private void uploadFumigationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadFumigationBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FumigationLoadFrame().setVisible(true);
    }//GEN-LAST:event_uploadFumigationBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InitialFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton requestBtn;
    private javax.swing.JButton setIndividualFumigationBtn;
    private javax.swing.JButton setPilotBtn;
    private javax.swing.JButton setProductBtn1;
    private javax.swing.JButton setTechnicBtn;
    private javax.swing.JButton uploadFumigationBtn;
    // End of variables declaration//GEN-END:variables
}
